
name: bikes-pipeline-test

on: push

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        run: |
          pip install -r requirements.txt
          
          dvc repro
          dvc push

          echo "# CML Report" > report.md
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md
