
name: bikes-pipeline-test

on: push

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        run: |
          pip install -r requirements.txt
          
          dvc dag
          dvc repro --dry
          git fetch --prune
          git config --global --add safe.directory /__w/pycon-za-test/pycon-za-test

          echo "# CML Report" > report.md
          dvc dag >> report.md
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md
